In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
from sklearn.datasets import load_diabetes
data=load_diabetes()
data

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06833155, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286131, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04688253,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452873, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00422151,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59

In [3]:
target=data['target'].reshape(-1,1)
target

array([[151.],
       [ 75.],
       [141.],
       [206.],
       [135.],
       [ 97.],
       [138.],
       [ 63.],
       [110.],
       [310.],
       [101.],
       [ 69.],
       [179.],
       [185.],
       [118.],
       [171.],
       [166.],
       [144.],
       [ 97.],
       [168.],
       [ 68.],
       [ 49.],
       [ 68.],
       [245.],
       [184.],
       [202.],
       [137.],
       [ 85.],
       [131.],
       [283.],
       [129.],
       [ 59.],
       [341.],
       [ 87.],
       [ 65.],
       [102.],
       [265.],
       [276.],
       [252.],
       [ 90.],
       [100.],
       [ 55.],
       [ 61.],
       [ 92.],
       [259.],
       [ 53.],
       [190.],
       [142.],
       [ 75.],
       [142.],
       [155.],
       [225.],
       [ 59.],
       [104.],
       [182.],
       [128.],
       [ 52.],
       [ 37.],
       [170.],
       [170.],
       [ 61.],
       [144.],
       [ 52.],
       [128.],
       [ 71.],
       [163.],
       [15

In [4]:
data['data'][0]

array([ 0.03807591,  0.05068012,  0.06169621,  0.02187239, -0.0442235 ,
       -0.03482076, -0.04340085, -0.00259226,  0.01990749, -0.01764613])

In [5]:
target.mean()

152.13348416289594

In [6]:
np.median(target)

140.5

In [7]:
target = np.where(target >= 140, 1, 0)
target

array([[1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
    

In [8]:
combined_data = np.concatenate((data['data'], target), axis=1)
combined_data[0][-1]

1.0

In [9]:
combined_data.shape

(442, 11)

In [10]:
#now the data is preprocessed and converted into categorical data, let us design a neural network
#before this lets split the data
x=combined_data[:,:-1]
y=combined_data[:,-1]
# y=y.reshape(-1,1)
x,y

(array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06833155, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286131, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04688253,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452873, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00422151,  0.00306441]]),
 array([1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 1., 1.,
        1., 0., 1., 0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 0., 1., 0.,
        0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1., 1.,
        1., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 0.,
        1., 1., 0., 1., 1., 0., 0., 0., 1., 1., 1., 0., 1., 0., 0., 1

In [11]:
len(x)

442

In [12]:
#splitting the dataset
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3,stratify=y)

In [13]:
len(x[0]),len(x_train[0])

(10, 10)

In [14]:
#initializing weights

In [15]:
def init():
    hidden_layer1 = np.zeros((5,1))
    weights1 = np.random.rand(5,(len(x[0])))-0.5
#     print(weights1)
    hidden_layer2 = np.zeros((3,1))
    weights2 = np.random.rand(3, 5)-0.5
    output_layer = np.zeros((1,1))
#     print(output_layer)
    op_weights = np.random.rand(1, 3)-0.5
    return weights1,weights2,op_weights,hidden_layer1,hidden_layer2,output_layer

In [16]:
#sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [17]:
def derivative_sigmoid(x):
    return sigmoid(x)*(1-sigmoid(x))

In [18]:
#relu activation function
def relu(x):
    return np.maximum(0, x)


In [19]:
def derivative_relu(x):
    return relu(x)>0

In [20]:
# Binary Cross-Entropy Loss
def bceloss(output, actual):
#     print("actual",actual.shape)
#     print("predicted",output.shape)
    value = -np.mean(actual * np.log(output) + (1 - actual) * np.log(1 - output))
    return value

In [21]:
def forward_prop(w1,w2,w3,b1,b2,b3,x):
    z1=np.dot(w1,x.T)+b1
    a1=relu(z1)
    z2=np.dot(w2,a1)+b2
    a2=relu(z2)
    z3=np.dot(w3,a2)+b3
    a3=relu(z3)
#     print(z1.shape)
#     print(z2.shape)
#     print(z3.shape)
    return z1,z2,z3,a1,a2,a3

In [99]:
def gradient(x,y,z1,z2,z3,a1,a2,a3,w1,w2,w3):
    de3=(a3-y)*derivative_sigmoid(z3)
    db3=de3
    dw3=np.dot(de3,a2.T)
    da2=np.dot(w3.T,de3)
#     print('Da2',da2.shape)
#     print('Dw3 ',dw3.shape)
#     print(w3.shape)
#     print(de3.shape)
    de2=da2*derivative_relu(z2)
    db2=de2
    dw2=np.dot(de2,a1.T)
    da1=np.dot(w2.T,de2)
#     print('Da1',da1.shape)
#     print('Dw2 ',dw2.shape)
#     print(w2.shape)
#     print(de2.shape)
#     print(z1.shape)

    de1=da1*derivative_relu(z1)
    db1=de1
    dw1=np.dot(de1,x)
#     print('Dw1',dw1.shape)
    return dw1,dw2,dw3,db1,db2,db3

In [23]:
# w1,w2,w3,b1,b2,b3=init()
# z1,z2,z3,a1,a2,a3=forward_prop(w1,w2,w3,b1,b2,b3,x)
# gradient(x,y,z1,z2,z3,a1,a2,a3,w1,w2,w3)

In [24]:
def updateWeightsAndBiases(w1,w2,w3,b1,b2,b3,dw1,dw2,dw3,db1,db2,db3,alpha):
    w1=w1-alpha*dw1
    b1=b1-alpha*db1
    w2=w2-alpha*dw2
    b2=b2-alpha*db2
    w3=w3-alpha*dw3
    b3=b3-alpha*db3
    return w1,w2,w3,b1,b2,b3

In [42]:
def predict(w1, w2, w3, b1, b2, b3, x):
    _, _, _, _, _, a3 = forward_prop(w1, w2, w3, b1, b2, b3, x)
    predictions = (a3 > 0.5).astype(int)
    return predictions

In [25]:
def accuracy(output, actual):
    predictions = (output > 0.5).astype(int)
    correct_predictions = np.mean(predictions == actual)
    return correct_predictions

In [100]:
alpha=0.1
epoch=50
w1,w2,w3,b1,b2,b3=init()
for i in range(epoch):
    z1,z2,z3,a1,a2,a3=forward_prop(w1,w2,w3,b1,b2,b3,x_train)
    dw1,dw2,dw3,db1,db2,db3=gradient(x_train,y_train,z1,z2,z3,a1,a2,a3,w1,w2,w3)
    w1,w2,w3,b1,b2,b3=updateWeightsAndBiases(w1,w2,w3,b1,b2,b3,dw1,dw2,dw3,db1,db2,db3,alpha)
    cost=bceloss(output=a3,actual=y_train)
    train_accuracy = accuracy(a3, y_train)
    print(f'Epoch {i+1}/{epoch}, Cost: {cost}, Accuracy: {train_accuracy}')

Epoch 1/50, Cost: nan, Accuracy: 0.49514563106796117
Epoch 2/50, Cost: nan, Accuracy: 0.49514563106796117
Epoch 3/50, Cost: nan, Accuracy: 0.49514563106796117
Epoch 4/50, Cost: nan, Accuracy: 0.49514563106796117
Epoch 5/50, Cost: nan, Accuracy: 0.49514563106796117
Epoch 6/50, Cost: nan, Accuracy: 0.49514563106796117
Epoch 7/50, Cost: nan, Accuracy: 0.49514563106796117
Epoch 8/50, Cost: nan, Accuracy: 0.49514563106796117
Epoch 9/50, Cost: nan, Accuracy: 0.49514563106796117
Epoch 10/50, Cost: nan, Accuracy: 0.49514563106796117
Epoch 11/50, Cost: nan, Accuracy: 0.49514563106796117
Epoch 12/50, Cost: nan, Accuracy: 0.49514563106796117
Epoch 13/50, Cost: nan, Accuracy: 0.49514563106796117
Epoch 14/50, Cost: nan, Accuracy: 0.49838187702265374
Epoch 15/50, Cost: nan, Accuracy: 0.5501618122977346
Epoch 16/50, Cost: nan, Accuracy: 0.7508090614886731
Epoch 17/50, Cost: nan, Accuracy: 0.9061488673139159
Epoch 18/50, Cost: nan, Accuracy: 0.9611650485436893
Epoch 19/50, Cost: nan, Accuracy: 0.97734

C:\Users\Kashyap Ghimire\AppData\Local\Temp\ipykernel_20456\248879514.py:5: RuntimeWarning: divide by zero encountered in log
  value = -np.mean(actual * np.log(output) + (1 - actual) * np.log(1 - output))
C:\Users\Kashyap Ghimire\AppData\Local\Temp\ipykernel_20456\248879514.py:5: RuntimeWarning: invalid value encountered in multiply
  value = -np.mean(actual * np.log(output) + (1 - actual) * np.log(1 - output))
C:\Users\Kashyap Ghimire\AppData\Local\Temp\ipykernel_20456\248879514.py:5: RuntimeWarning: invalid value encountered in log
  value = -np.mean(actual * np.log(output) + (1 - actual) * np.log(1 - output))


The value of BCE loss is nan because of some values that are equal to zero

To overcome this let us implement a different cost function suitable for binary classification

In [101]:
a3

array([[1.00006578e+00, 1.00020646e+00, 0.00000000e+00, 9.99860577e-01,
        9.99602942e-01, 1.85947425e-04, 2.66097181e-04, 9.99887077e-01,
        0.00000000e+00, 0.00000000e+00, 2.98382447e-04, 1.00019743e+00,
        1.00005317e+00, 2.29076002e-04, 1.93568656e-05, 3.64012205e-04,
        1.00020603e+00, 0.00000000e+00, 7.73567686e-04, 1.00027239e+00,
        1.00019929e+00, 1.09416356e-05, 0.00000000e+00, 1.00009699e+00,
        1.00015453e+00, 1.00026405e+00, 1.22977343e-04, 1.00010137e+00,
        1.00014553e+00, 1.00006767e+00, 4.18851603e-04, 1.00009686e+00,
        1.00008653e+00, 1.00009148e+00, 7.09947768e-06, 6.92109592e-01,
        5.45341004e-04, 1.00005434e+00, 1.00022504e+00, 1.00009301e+00,
        1.00002951e+00, 3.44644010e-04, 8.49765980e-05, 1.00009209e+00,
        1.56220064e-03, 0.00000000e+00, 9.99995724e-01, 1.00014422e+00,
        1.84201587e-04, 1.00014325e+00, 1.00004990e+00, 9.99912450e-01,
        4.24155878e-05, 0.00000000e+00, 9.12390897e-04, 5.266672

In [102]:
b=np.zeros((a3.size))
i=0
for item in a3[0]:
    if item>0.5:
        b[i]=1
    else:
        b[i]=0
    i+=1
b

array([1., 1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 1.,
       0., 0., 1., 1., 0., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1.,
       0., 1., 0., 1., 1., 1., 1., 0., 0., 1., 0., 0., 1., 1., 0., 1., 1.,
       1., 0., 0., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1.,
       1., 1., 1., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0.,
       0., 1., 1., 1., 0., 1., 0., 0., 1., 1., 1., 0., 1., 1., 0., 0., 1.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 1.,
       0., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 1., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0., 0., 1., 0., 0., 0.,
       1., 1., 1., 0., 1., 1., 0., 0., 0., 1., 1., 1., 0., 1., 1., 0., 0.,
       0., 1., 0., 0., 1., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 1., 0., 1., 1., 1., 0., 0., 1., 0.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0.,
       1., 1., 0., 1., 0.

In [103]:
y_train

array([1., 1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 1.,
       0., 0., 1., 1., 0., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1.,
       0., 1., 0., 1., 1., 1., 1., 0., 0., 1., 0., 0., 1., 1., 0., 1., 1.,
       1., 0., 0., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1.,
       1., 1., 1., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0.,
       0., 1., 1., 1., 0., 1., 0., 0., 1., 1., 1., 0., 1., 1., 0., 0., 1.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 1.,
       0., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 1., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0., 0., 1., 0., 0., 0.,
       1., 1., 1., 0., 1., 1., 0., 0., 0., 1., 1., 1., 0., 1., 1., 0., 0.,
       0., 1., 0., 0., 1., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 1., 0., 1., 1., 1., 0., 0., 1., 0.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0.,
       1., 1., 0., 1., 0.

In [ ]:
#to predicr

In [45]:
x_test.shape

(133, 10)

In [46]:
x_train.shape

(309, 10)

predicting values from test set

In [47]:
# y_pred = predict(w1, w2, w3, b1, b2, b3, x_test)
# print("Predicted labels:", y_pred)

ValueError: operands could not be broadcast together with shapes (5,133) (5,309) 

In [86]:
#to fix this we add 0 padding to the test set
def change_shape(x_test):
    desired_shape = (309, 10)

    # Calculate padding
    pad_width = [(0, desired_shape[0] - x_test.shape[0]), (0, 0)]

    # Pad the array with zeros
    new_x_test = np.pad(x_test, pad_width, mode='constant', constant_values=0)

    print("Original shape:", x_test.shape)
    print("Padded shape:", new_x_test.shape)
    return new_x_test

The above given code throws an error because the matrix used to train the network has different dimensions compared to the one that is used to test

In [106]:
new_x_test=change_shape(x_test)
y_pred = predict(w1, w2, w3, b1, b2, b3, new_x_test)
print("Predicted labels:", y_pred)

Original shape: (133, 10)
Padded shape: (309, 10)
Predicted labels: [[1 1 0 1 1 0 0 1 0 0 0 1 1 0 0 0 1 0 0 1 1 0 0 1 1 1 0 1 1 1 0 1 1 1 0 1
  0 1 1 1 1 0 0 1 0 0 1 1 0 1 1 1 0 0 0 0 1 1 0 1 1 1 0 0 0 1 0 1 1 1 1 0
  0 0 1 0 1 1 0 1 0 1 0 1 0 0 1 1 1 0 1 0 0 1 1 1 0 1 1 0 0 1 0 1 0 0 0 0
  0 0 0 1 0 0 0 0 1 1 1 0 1 1 1 1 0 1 0 1 1 1 0 1 0 0 0 1 0 0 0 0 0 1 0 1
  1 1 0 0 0 1 0 0 0 1 1 1 0 1 1 0 0 0 1 1 1 0 1 1 0 0 0 1 0 0 1 1 0 0 1 0
  1 1 1 1 1 0 0 0 0 1 1 0 1 0 0 1 0 1 1 1 0 0 1 0 0 1 1 1 1 1 1 1 1 0 0 0
  0 1 1 0 0 1 1 0 1 0 0 0 1 0 1 0 1 1 0 0 1 1 1 0 0 0 0 0 0 1 0 1 0 1 0 1
  1 1 0 0 0 1 0 1 0 0 1 1 1 0 1 1 0 0 1 0 1 0 0 0 1 0 0 0 1 0 1 1 0 0 1 1
  0 1 1 1 0 0 1 0 0 1 1 1 0 0 1 0 1 0 1 1 1]]


In [107]:
#however the predicted values are top 133 values of the network
print("The actal labels are: ", y_test)
print("The predicted labels are: ",y_pred[0:,:133])

The actal labels are:  [0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0. 1. 0. 0.
 1. 0. 0. 1. 1. 1. 1. 1. 0. 0. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0. 1. 0. 0. 1.
 1. 0. 1. 1. 0. 0. 1. 0. 0. 1. 0. 1. 1. 0. 1. 1. 1. 0. 0. 0. 0. 1. 1. 1.
 0. 0. 0. 1. 1. 0. 1. 0. 0. 0. 1. 0. 1. 1. 1. 0. 0. 1. 1. 0. 1. 0. 1. 0.
 0. 0. 1. 0. 1. 0. 1. 1. 1. 0. 0. 1. 0. 1. 0. 0. 1. 1. 1. 0. 1. 1. 0. 0.
 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 0.]
The predicted labels are:  [[1 1 0 1 1 0 0 1 0 0 0 1 1 0 0 0 1 0 0 1 1 0 0 1 1 1 0 1 1 1 0 1 1 1 0 1
  0 1 1 1 1 0 0 1 0 0 1 1 0 1 1 1 0 0 0 0 1 1 0 1 1 1 0 0 0 1 0 1 1 1 1 0
  0 0 1 0 1 1 0 1 0 1 0 1 0 0 1 1 1 0 1 0 0 1 1 1 0 1 1 0 0 1 0 1 0 0 0 0
  0 0 0 1 0 0 0 0 1 1 1 0 1 1 1 1 0 1 0 1 1 1 0 1 0]]


In [108]:
#hence the model has overfit
#to check this

In [110]:
alpha=0.012
epoch=145
w1,w2,w3,b1,b2,b3=init()
for i in range(epoch):
    z1,z2,z3,a1,a2,a3=forward_prop(w1,w2,w3,b1,b2,b3,x_train)
    dw1,dw2,dw3,db1,db2,db3=gradient(x_train,y_train,z1,z2,z3,a1,a2,a3,w1,w2,w3)
    w1,w2,w3,b1,b2,b3=updateWeightsAndBiases(w1,w2,w3,b1,b2,b3,dw1,dw2,dw3,db1,db2,db3,alpha)
    cost=bceloss(output=a3,actual=y_train)
    train_accuracy = accuracy(a3, y_train)
    print(f'Epoch {i+1}/{epoch}, Cost: {cost}, Accuracy: {train_accuracy}')

Epoch 1/145, Cost: nan, Accuracy: 0.49514563106796117
Epoch 2/145, Cost: nan, Accuracy: 0.49514563106796117
Epoch 3/145, Cost: nan, Accuracy: 0.49514563106796117
Epoch 4/145, Cost: nan, Accuracy: 0.49514563106796117
Epoch 5/145, Cost: nan, Accuracy: 0.49514563106796117
Epoch 6/145, Cost: nan, Accuracy: 0.49514563106796117
Epoch 7/145, Cost: nan, Accuracy: 0.49514563106796117
Epoch 8/145, Cost: nan, Accuracy: 0.49514563106796117
Epoch 9/145, Cost: nan, Accuracy: 0.49514563106796117
Epoch 10/145, Cost: nan, Accuracy: 0.49514563106796117
Epoch 11/145, Cost: nan, Accuracy: 0.49514563106796117
Epoch 12/145, Cost: nan, Accuracy: 0.49514563106796117
Epoch 13/145, Cost: nan, Accuracy: 0.49514563106796117
Epoch 14/145, Cost: nan, Accuracy: 0.49514563106796117
Epoch 15/145, Cost: nan, Accuracy: 0.49514563106796117
Epoch 16/145, Cost: nan, Accuracy: 0.49514563106796117
Epoch 17/145, Cost: nan, Accuracy: 0.49514563106796117
Epoch 18/145, Cost: nan, Accuracy: 0.49514563106796117
Epoch 19/145, Cost:

C:\Users\Kashyap Ghimire\AppData\Local\Temp\ipykernel_20456\248879514.py:5: RuntimeWarning: divide by zero encountered in log
  value = -np.mean(actual * np.log(output) + (1 - actual) * np.log(1 - output))
C:\Users\Kashyap Ghimire\AppData\Local\Temp\ipykernel_20456\248879514.py:5: RuntimeWarning: invalid value encountered in multiply
  value = -np.mean(actual * np.log(output) + (1 - actual) * np.log(1 - output))
C:\Users\Kashyap Ghimire\AppData\Local\Temp\ipykernel_20456\248879514.py:5: RuntimeWarning: invalid value encountered in log
  value = -np.mean(actual * np.log(output) + (1 - actual) * np.log(1 - output))


In [111]:
#the model got 96 percent accuracy
new_x_test=change_shape(x_test)
y_pred = predict(w1, w2, w3, b1, b2, b3, new_x_test)
print("The actal labels are: ", y_test)
print("The predicted labels are: ",y_pred[0:,:133])


Original shape: (133, 10)
Padded shape: (309, 10)
The actal labels are:  [0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0. 1. 0. 0.
 1. 0. 0. 1. 1. 1. 1. 1. 0. 0. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0. 1. 0. 0. 1.
 1. 0. 1. 1. 0. 0. 1. 0. 0. 1. 0. 1. 1. 0. 1. 1. 1. 0. 0. 0. 0. 1. 1. 1.
 0. 0. 0. 1. 1. 0. 1. 0. 0. 0. 1. 0. 1. 1. 1. 0. 0. 1. 1. 0. 1. 0. 1. 0.
 0. 0. 1. 0. 1. 0. 1. 1. 1. 0. 0. 1. 0. 1. 0. 0. 1. 1. 1. 0. 1. 1. 0. 0.
 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 0.]
The predicted labels are:  [[1 1 0 1 1 0 0 0 0 0 0 1 1 0 0 0 1 0 0 1 1 0 0 1 1 0 0 1 1 1 0 0 1 1 0 1
  0 1 1 1 1 0 1 1 0 0 1 1 0 1 1 1 0 0 0 0 1 1 0 1 1 0 0 0 0 1 0 1 1 1 1 0
  0 0 0 0 1 1 0 1 0 0 0 1 0 0 1 1 1 0 1 0 0 1 1 1 0 1 1 0 0 1 0 1 0 0 0 0
  0 0 0 1 0 0 0 0 1 1 1 0 1 1 1 1 0 1 0 1 1 1 0 1 0]]


hence The model performs poorly on test data but performs good on train data(the model is overfit)

In [112]:
np.savez('weights.npz', w1=w1, w2=w2,w3=w3, b1=b1,b2=b2,b3=b3)