# 4. Combining arrays

We have already seen how to create arrays and how to modify their dimensions. One last operation we can do is to combine multiple arrays. There are two ways to do that: by assembling arrays of same dimensions (concatenation, stacking etc.) or by combining arrays of different dimensions using *broadcasting*. Like in the previous chapter, we illustrate with small arrays and a real image.

In [42]:
import numpy as np


## 4.1 Arrays of same dimensions

Let's start by creating a few two 2D arrays:

In [43]:
array1 = np.ones((10,5))
array2 = 2*np.ones((10,3))
array3 = 3*np.ones((10,5))

### 4.1.1 Concatenation

The first operation we can perform is concatenation, i.e. assembling the two 2D arrays into a larger 2D array. Of course we have to be careful with the size of each dimension. For example if we try to concatenate ```array1``` and ```array2``` along the first dimension, we get:

In [44]:
np.concatenate([array1, array2])

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 5 and the array at index 1 has size 3

Both array have 10 lines, but one has 3 and the other 5 columns. We can therefore only concatenate them along the second dimensions:

In [45]:
array_conc = np.concatenate([array1, array2], axis = 1) #concatinates array 2 with array 1 on a row wise basis

In [46]:
array_conc.shape

(10, 8)

In [47]:
#concatinating with axis 1 gives row wise concat

In [48]:
np.concatenate([array1,array3],axis=1)

array([[1., 1., 1., 1., 1., 3., 3., 3., 3., 3.],
       [1., 1., 1., 1., 1., 3., 3., 3., 3., 3.],
       [1., 1., 1., 1., 1., 3., 3., 3., 3., 3.],
       [1., 1., 1., 1., 1., 3., 3., 3., 3., 3.],
       [1., 1., 1., 1., 1., 3., 3., 3., 3., 3.],
       [1., 1., 1., 1., 1., 3., 3., 3., 3., 3.],
       [1., 1., 1., 1., 1., 3., 3., 3., 3., 3.],
       [1., 1., 1., 1., 1., 3., 3., 3., 3., 3.],
       [1., 1., 1., 1., 1., 3., 3., 3., 3., 3.],
       [1., 1., 1., 1., 1., 3., 3., 3., 3., 3.]])

In [49]:
##concatinating with axis 0 gives column wise concat or stack ko format ma halxa without increasing the dimension

In [50]:
np.concatenate([array1,array3],axis=0)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [51]:
array_conc

array([[1., 1., 1., 1., 1., 2., 2., 2.],
       [1., 1., 1., 1., 1., 2., 2., 2.],
       [1., 1., 1., 1., 1., 2., 2., 2.],
       [1., 1., 1., 1., 1., 2., 2., 2.],
       [1., 1., 1., 1., 1., 2., 2., 2.],
       [1., 1., 1., 1., 1., 2., 2., 2.],
       [1., 1., 1., 1., 1., 2., 2., 2.],
       [1., 1., 1., 1., 1., 2., 2., 2.],
       [1., 1., 1., 1., 1., 2., 2., 2.],
       [1., 1., 1., 1., 1., 2., 2., 2.]])

### 4.1.2 Stacking

If we have several arrays with exact same sizes, we can also *stack* them, i.e. assemble them along a *new* dimension. For example we can create a 3D stack out of two 2D arrays:

In [52]:
array_stack = np.stack([array1, array3],axis=1)

In [53]:
array_stack.shape

(10, 2, 5)

In [54]:
array_stack

array([[[1., 1., 1., 1., 1.],
        [3., 3., 3., 3., 3.]],

       [[1., 1., 1., 1., 1.],
        [3., 3., 3., 3., 3.]],

       [[1., 1., 1., 1., 1.],
        [3., 3., 3., 3., 3.]],

       [[1., 1., 1., 1., 1.],
        [3., 3., 3., 3., 3.]],

       [[1., 1., 1., 1., 1.],
        [3., 3., 3., 3., 3.]],

       [[1., 1., 1., 1., 1.],
        [3., 3., 3., 3., 3.]],

       [[1., 1., 1., 1., 1.],
        [3., 3., 3., 3., 3.]],

       [[1., 1., 1., 1., 1.],
        [3., 3., 3., 3., 3.]],

       [[1., 1., 1., 1., 1.],
        [3., 3., 3., 3., 3.]],

       [[1., 1., 1., 1., 1.],
        [3., 3., 3., 3., 3.]]])

We can select the dimension along which to stack, again by using the ```axis``` keyword. For example if we want our new dimensions to be the *third* axis we can write:

In [55]:
array_stack = np.stack([array1, array3], axis = 2)

In [56]:
array_stack.shape

(10, 5, 2)

In [57]:
array_stack

array([[[1., 3.],
        [1., 3.],
        [1., 3.],
        [1., 3.],
        [1., 3.]],

       [[1., 3.],
        [1., 3.],
        [1., 3.],
        [1., 3.],
        [1., 3.]],

       [[1., 3.],
        [1., 3.],
        [1., 3.],
        [1., 3.],
        [1., 3.]],

       [[1., 3.],
        [1., 3.],
        [1., 3.],
        [1., 3.],
        [1., 3.]],

       [[1., 3.],
        [1., 3.],
        [1., 3.],
        [1., 3.],
        [1., 3.]],

       [[1., 3.],
        [1., 3.],
        [1., 3.],
        [1., 3.],
        [1., 3.]],

       [[1., 3.],
        [1., 3.],
        [1., 3.],
        [1., 3.],
        [1., 3.]],

       [[1., 3.],
        [1., 3.],
        [1., 3.],
        [1., 3.],
        [1., 3.]],

       [[1., 3.],
        [1., 3.],
        [1., 3.],
        [1., 3.],
        [1., 3.]],

       [[1., 3.],
        [1., 3.],
        [1., 3.],
        [1., 3.],
        [1., 3.]]])

In [58]:
array_stack = np.stack([array1, array3], axis = 0)

In [59]:
array_stack.shape

(2, 10, 5)

In [60]:
array_stack

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]]])

## 4.2 Arrays of different dimensions

**bold text**### 4.2.1 Broadcasting

Numpy has a powerful feature called **broadcasting**. This is the feature that for example allows you to write:

In [61]:
2 * array1

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

Here we just combined a single number with an array and Numpy *re-used* or *broadcasted* the element with less dimensions (the number 2) across the entire ```array1```. This does not only work with single numbers but also with arrays of different dimensions. Broadcasting can become very complex, so we limit ourselves here to a few common examples.

The general rule is that in an operation with arrays of different dimensions, **missing dimensions** or **dimensions of size 1** get *repeated* to create two arrays of same size. Note that comparisons of dimension size start from the **last** dimensions. For example if we have a 1D array and a 2D array:

In [62]:
array1D = np.arange(4)
array1D

array([0, 1, 2, 3])

In [63]:
array2D = np.ones((6,4))
array2D

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [64]:
array1D * array2D

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.]])

Here ```array1D``` which has a *single line* got *broadcasted* over *each line* of the 2D array ```array2D```. Note the the size of each dimension is important. If ```array1D``` had for example more columns, that broadcasting could not work:

In [65]:
array1D = np.arange(3)
array1D

array([0, 1, 2])

In [66]:
array1D * array2D

ValueError: operands could not be broadcast together with shapes (3,) (6,4) 

As mentioned above, dimension sizes comparison start from the last dimension, so for example if ```array1D``` had a length of 6, like the first dimension of ```array2D```, broadcasting would fail:

In [67]:
#2 input 3d arrays

m=np.array([[[1,2,3],[4,5,6],[7,8,9]],

			[[10,11,12],[13,14,15],[16,17,18]]])

n=np.array([[[51,52,53],[54,55,56],[57,58,59]],
            [[110,111,112],[113,114,115],[116,117,118]]])

# stacking
np.stack((m,n),axis=0)


array([[[[  1,   2,   3],
         [  4,   5,   6],
         [  7,   8,   9]],

        [[ 10,  11,  12],
         [ 13,  14,  15],
         [ 16,  17,  18]]],


       [[[ 51,  52,  53],
         [ 54,  55,  56],
         [ 57,  58,  59]],

        [[110, 111, 112],
         [113, 114, 115],
         [116, 117, 118]]]])

In [71]:
np.stack((m,n),axis=0).shape

(2, 2, 3, 3)

In [68]:
np.stack((m,n),axis=1)

array([[[[  1,   2,   3],
         [  4,   5,   6],
         [  7,   8,   9]],

        [[ 51,  52,  53],
         [ 54,  55,  56],
         [ 57,  58,  59]]],


       [[[ 10,  11,  12],
         [ 13,  14,  15],
         [ 16,  17,  18]],

        [[110, 111, 112],
         [113, 114, 115],
         [116, 117, 118]]]])

In [69]:
np.stack((m,n),axis=2)

array([[[[  1,   2,   3],
         [ 51,  52,  53]],

        [[  4,   5,   6],
         [ 54,  55,  56]],

        [[  7,   8,   9],
         [ 57,  58,  59]]],


       [[[ 10,  11,  12],
         [110, 111, 112]],

        [[ 13,  14,  15],
         [113, 114, 115]],

        [[ 16,  17,  18],
         [116, 117, 118]]]])

In [70]:
np.stack((m,n),axis=2).shape

(2, 3, 2, 3)

In [73]:
np.stack((m,n),axis=3)

array([[[[  1,  51],
         [  2,  52],
         [  3,  53]],

        [[  4,  54],
         [  5,  55],
         [  6,  56]],

        [[  7,  57],
         [  8,  58],
         [  9,  59]]],


       [[[ 10, 110],
         [ 11, 111],
         [ 12, 112]],

        [[ 13, 113],
         [ 14, 114],
         [ 15, 115]],

        [[ 16, 116],
         [ 17, 117],
         [ 18, 118]]]])