In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import matplotlib.pyplot as plt
import numpy as np
from sklearn.datasets import load_digits
db = load_digits()
db.images[0].shape

(8, 8)

In [2]:
input_dim=8*8
output_layers=10

In [3]:
db['data'][0]

array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
       15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
       12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
        0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
       10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.])

In [4]:
db['target']

array([0, 1, 2, ..., 8, 9, 8])

In [5]:
target=db['target'].reshape(-1,1)
data=np.concatenate((db['data'], target), axis=1)
data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.],
       [ 0.,  0.,  0., ...,  9.,  0.,  2.],
       ...,
       [ 0.,  0.,  1., ...,  0.,  0.,  8.],
       [ 0.,  0.,  2., ...,  0.,  0.,  9.],
       [ 0.,  0., 10., ...,  1.,  0.,  8.]])

In [6]:
X=data[:,:-1]
Y=data[:,-1]

In [7]:
x= torch.tensor(X, dtype=torch.float32)
y=torch.tensor(Y, dtype=torch.long)

In [8]:
RANDOM_STATE=np.random.seed(7)

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=RANDOM_STATE,stratify=y)


In [10]:
class MLP(nn.Module):
    def __init__(self, input_dim):
        super(MLP, self).__init__()
        self.fc = nn.Linear(input_dim, 16)  
        self.op = nn.Linear(16, 10)          
    def forward(self, x):
        x = torch.relu(self.fc(x))
        x = torch.softmax(self.op(x),dim=1)
        return x

In [11]:
def train_mlp(model, criterion, optimizer, data, targets, epochs=1000):
    for epoch in range(epochs):
        model.train()
        
        optimizer.zero_grad()
        
        # Forward pass
        outputs = model(data)
        loss = criterion(outputs, targets)
        
        # Backward pass and optimization
        loss.backward()
        optimizer.step()
        
        if (epoch+1) % 100 == 0:
            print(f'Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}')

In [12]:
def test_mlp(model, data):
    model.eval()
    with torch.no_grad():
        outputs = model(data)
        predicted = outputs.round().squeeze()
        return predicted


In [13]:
mlp = MLP(input_dim)
# Define loss and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(mlp.parameters(), lr=0.1)

In [14]:
train_mlp(mlp, criterion, optimizer, x_train,y_train, epochs=20000)

Epoch [100/20000], Loss: 2.2618
Epoch [200/20000], Loss: 2.2609
Epoch [300/20000], Loss: 2.2604
Epoch [400/20000], Loss: 2.2606
Epoch [500/20000], Loss: 2.2605
Epoch [600/20000], Loss: 2.2606
Epoch [700/20000], Loss: 2.2606
Epoch [800/20000], Loss: 2.2606
Epoch [900/20000], Loss: 2.2607
Epoch [1000/20000], Loss: 2.2607
Epoch [1100/20000], Loss: 2.2621
Epoch [1200/20000], Loss: 2.2606
Epoch [1300/20000], Loss: 2.0143
Epoch [1400/20000], Loss: 1.9684
Epoch [1500/20000], Loss: 1.9657
Epoch [1600/20000], Loss: 1.9670
Epoch [1700/20000], Loss: 1.9642
Epoch [1800/20000], Loss: 1.9663
Epoch [1900/20000], Loss: 1.9650
Epoch [2000/20000], Loss: 1.9616
Epoch [2100/20000], Loss: 1.8905
Epoch [2200/20000], Loss: 1.8905
Epoch [2300/20000], Loss: 1.8947
Epoch [2400/20000], Loss: 1.9002
Epoch [2500/20000], Loss: 1.8967
Epoch [2600/20000], Loss: 1.8933
Epoch [2700/20000], Loss: 1.9051
Epoch [2800/20000], Loss: 1.8884
Epoch [2900/20000], Loss: 1.8766
Epoch [3000/20000], Loss: 1.8780
Epoch [3100/20000],